# 50 条中英混杂 + 技术/专业术语 测试句
SENTENCES = [
    "我用 Python 写了一个爬虫，把数据存到 MySQL 里。",
    "这个 API 返回的是 JSON 格式，记得做好异常处理。",
    "我们用 Docker 把服务打包，然后部署到 Kubernetes 集群上。",
    "前端用 React，后端用 Node.js，数据库选了 PostgreSQL。",
    "你把这个 bug 修一下，然后提个 pull request 给我 review。",
    "这段代码的时间复杂度太高了，建议改用哈希表优化。",
    "服务器的 CPU 占用率飙到百分之九十，可能有内存泄漏。",
    "我们的 model 在测试集上的 accuracy 达到了百分之九十五。",
    "用 Redis 做缓存可以显著降低数据库的 latency。",
    "这个 function 有 side effect，最好改成纯函数。",
    "我把 feature branch merge 到 main 之前先跑一遍 CI。",
    "Transformer 的 attention 机制是这篇论文的核心创新。",
    "你检查一下 nginx 的配置，反向代理好像没生效。",
    "这个项目用了 microservices 架构，服务之间通过 gRPC 通信。",
    "把 log level 调成 debug，方便我们定位问题。",
    "我们需要做一次 code review，顺便重构一下这个 module。",
    "GPU 显存不够了，把 batch size 调小一点试试。",
    "这个 SQL 查询没走索引，所以特别慢。",
    "用 TypeScript 能在编译期就发现很多类型错误。",
    "我们的 CDN 节点覆盖全球，静态资源加载很快。",
    "这个 endpoint 需要鉴权，记得在 header 里带上 token。",
    "机器学习里 overfitting 是个常见问题，可以用 dropout 缓解。",
    "把这个组件抽成一个可复用的 hook，逻辑会清晰很多。",
    "我们用 Kafka 做消息队列，处理高并发的事件流。",
    "这个算法用了动态规划，把子问题的结果 cache 起来。",
    "部署的时候记得设置好环境变量，别把 secret 写死在代码里。",
    "这次性能优化主要是减少了不必要的 re-render。",
    "我们的数据 pipeline 是用 Airflow 来调度的。",
    "这个接口有 race condition，需要加个锁来保证线程安全。",
    "用 webpack 打包之后，记得开启 tree shaking 减小体积。",
    "这个 PR 里有个 typo，变量名拼错了。",
    "我们把单体应用拆成了几个独立的 service。",
    "这个 query 应该用 join 而不是写好几个子查询。",
    "训练的时候 loss 一直不收敛，可能是 learning rate 太大了。",
    "把 HTTPS 证书配好，不然浏览器会报警告。",
    "这个 library 有个已知的 vulnerability，赶紧升级版本。",
    "我们用 Prometheus 加 Grafana 来做监控和告警。",
    "这段逻辑放在 middleware 里处理会更合适。",
    "数据库做了读写分离，read replica 分担了查询压力。",
    "这个深度学习模型用的是 ResNet 作为 backbone。",
    "你先把 dependency 装好，再运行这个 script。",
    "我们的 CI/CD 流水线是用 GitHub Actions 搭的。",
    "这个 bug 只在 production 环境复现，本地跑没问题。",
    "用 async await 写异步代码比 callback 清晰太多了。",
    "这个表的数据量太大了，得考虑做分库分表。",
    "我们用 OAuth 做第三方登录的授权。",
    "这个 component 的 state 管理用 Redux 有点重，换成 Zustand 吧。",
    "把缓存策略改成 LRU，命中率会更高。",
    "这个模型推理太慢，可以试试量化或者蒸馏。",
    "我们的 backend 用 Go 重写之后，吞吐量提升了好几倍。",
]
assert len(SENTENCES) == 50, len(SENTENCES)
